// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlanmmbgyyxuqvezudir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYW5tbWJneXl4dXF2ZXp1ZGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MDU4MzUsImV4cCI6MjA4NDA4MTgzNX0.L_r_WHXWw9BhJ4sR4ozkYKbseLkGtJ79skMD10IwdVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});